# OPTIONAL DEFINITIONS
output_file: findings.json
tool_version: undefined

# MANDATORY DEFINITIONS
directories:
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/AndroGoat
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/http4k-webgoat
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/habitica-android
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/Goatlin
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/NotyKT
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/ivy-wallet
  - /Users/lironbiam/Documents/GoatRepositories/Kotlin/ytvanced
tool_cmd:
  - semgrep
  - scan
  - --config=/Users/lironbiam/Documents/SummarizeFindings/rulesets/sql2.yaml
  - --verbose
  - --output=./{output_file}
  - --json
  - --severity=ERROR
  - --severity=WARNING
headers:
  - severity
  - path
  - line
  - lines
  - message
jq_cmd:
  - jq
  - '[.results[] | {lines: .extra.lines, message: .extra.message, severity: .extra.severity, path: .path, line: .start.line}]'
