# OPTIONAL DEFINITIONS
output_file: findings.json
tool_version: undefined

# MANDATORY DEFINITIONS
directories:
  - C:/Users/97250/Documents/Microsoft VS Code/vsProjects/@DRAFTS/NodeGoat
  - C:/Users/97250/Documents/Files/VulnerableProjects/pygoat
tool_cmd:
  - docker
  - run
  - --rm
  - -v
  - ${PWD}:/path
  - zricethezav/gitleaks:latest
  - detect
  - --source
  - /path
  - -v
headers:
  - severity
  - impact
  - confidence
  - path
  - line
  - lines
  - message
jq_cmd:
  - jq
  - '[.results[] | {lines: .extra.lines, message: .extra.message, severity: .extra.severity, path: .path, line: .start.line, impact: .extra.metadata.impact, confidence: .extra.metadata.confidence}]'