# OPTIONAL DEFINITIONS
output_file: findings.json
tool_version: undefined

# MANDATORY DEFINITIONS
directories:
  - PATH/AndroGoat
  - PATH/habitica-android
  - PATH/Goatlin
  - PATH/NotyKT
  - PATH/ivy-wallet
  - PATH/ytvanced
tool_cmd:
  - horusec
  - start
  - -p=.
  - -o=json
  - -O=./{output_file}
  - -s=LOW
headers:
  - severity
  - language
  - confidence
  - code
  - details
jq_cmd:
  - jq
  - '[.analysisVulnerabilities[].vulnerabilities | {severity, language, confidence, code, details}]'