# OPTIONAL DEFINITIONS
output_file: findings.json
tool_version: undefined

# MANDATORY DEFINITIONS
directories:
  - PATH/AndroGoat
  - PATH/http4k-webgoat
  - PATH/Exposed
  - PATH/habitica-android
  - PATH/Goatlin
  - PATH/NotyKT
  - PATH/ivy-wallet
  - PATH/ytvanced
tool_cmd:
  - semgrep
  - scan
  - --config=/Users/lironbiam/Documents/SummarizeFindings/rulesets/kotlin-rules.yaml
  - --verbose
  - --output=./{output_file}
  - --json
  - --severity=ERROR
  - --severity=WARNING
headers:
  - severity
  - impact
  - confidence
  - path
  - line
  - lines
  - message
jq_cmd:
  - jq
  - '[.results[] | {lines: .extra.lines, message: .extra.message, severity: .extra.severity, path: .path, line: .start.line, impact: .extra.metadata.impact, confidence: .extra.metadata.confidence}]'